#! /bin/sh

if [[ "$1" == "build" ]]; then
  make ARCH=arm CROSS_COMPILE=arm-none-eabi- all
elif [[ "$1" == "run" ]]; then
  cd arch/arm/boot
  qemu-system-arm -M versatilepb -m 128M -kernel zImage -initrd rootfs -append "root=/dev/ram rdinit=/test" -s
elif [[ "$1" == "runS" ]]; then
  cd arch/arm/boot
  qemu-system-arm -M versatilepb -m 128M -kernel zImage -initrd rootfs -append "root=/dev/ram rdinit=/test" -s -S
fi
